// RootLayout.js
import Head from 'next/head';
import { Roboto } from 'next/font/google';
import './globals.css';

const Roboto1 = Roboto({ subsets: ['latin'] ,weight:["100","700","400","300"]});

export const metadata = {
  title: 'WhatsApp',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>

      </Head>
      <body className={Roboto1.className}>{children}</body>
    </html>
  );
}
